# Generated by Django 5.2.5 on 2025-09-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('cuerpo', models.TextField()),
                ('categoria', models.CharField(max_length=20)),
                ('vigente_desde', models.DateTimeField(auto_now_add=True)),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='PUBLICADO', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(blank=True, db_column='condominio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedades.condominio')),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'avisos',
            },
        ),
        migrations.CreateModel(
            name='AvisoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('mime', models.CharField(max_length=60)),
                ('aviso', models.ForeignKey(db_column='aviso_id', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='comunicacion.aviso')),
            ],
            options={
                'db_table': 'avisos_adjuntos',
            },
        ),
        migrations.CreateModel(
            name='AvisoDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(max_length=12)),
                ('aviso', models.ForeignKey(db_column='aviso_id', on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='comunicacion.aviso')),
                ('unidad', models.ForeignKey(blank=True, db_column='unidad_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.unidad')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'avisos_destinatarios',
            },
        ),
    ]
