# Generated by Django 5.2.5 on 2025-08-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=100)),
                ('poder', models.IntegerField()),
            ],
        ),
    ]
