# Generated by Django 5.2.6 on 2025-09-13 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.TextField(unique=True)),
                ('correo', models.TextField(unique=True)),
                ('nombre_completo', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('hash_contrasena', models.TextField()),
                ('activo', models.BooleanField()),
                ('ultimo_login_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='myapp',
        ),
    ]
