# Generated by Django 5.2.5 on 2025-09-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuentaUnidad',
            fields=[
                ('cargo_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('unidad_id', models.IntegerField()),
                ('concepto_id', models.SmallIntegerField()),
                ('periodo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recargo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('estado_registrado', models.CharField(max_length=12)),
                ('pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_calculado', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'vw_estado_cuenta_unidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'conceptos',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADO', 'PAGADO'), ('ANULADO', 'ANULADO')], default='PENDIENTE', max_length=12)),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, to='propiedades.unidad')),
                ('concepto', models.ForeignKey(db_column='concepto_id', on_delete=django.db.models.deletion.PROTECT, to='finanzas.concepto')),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=40)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('RECIBO', 'RECIBO'), ('FACTURA', 'FACTURA')], max_length=12)),
                ('moneda', models.CharField(default='BOB', max_length=8)),
                ('condominio', models.ForeignKey(blank=True, db_column='condominio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedades.condominio')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoArchivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('PNG', 'PNG'), ('JPG', 'JPG'), ('XML', 'XML')], max_length=15)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, to='finanzas.documento')),
            ],
            options={
                'db_table': 'documentos_archivos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('QR', 'QR'), ('TARJETA', 'TARJETA'), ('BILLETERA', 'BILLETERA')], max_length=15)),
                ('estado', models.CharField(choices=[('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('PENDIENTE', 'PENDIENTE')], default='APROBADO', max_length=12)),
                ('pasarela', models.CharField(blank=True, max_length=40, null=True)),
                ('transaccion_id', models.CharField(blank=True, max_length=80, null=True)),
                ('ref_externa', models.CharField(blank=True, max_length=120, null=True)),
                ('documento', models.ForeignKey(blank=True, db_column='documento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.documento')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cargo', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.RESTRICT, to='finanzas.cargo')),
                ('pago', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, to='finanzas.pago')),
            ],
            options={
                'db_table': 'pagos_detalle',
            },
        ),
        migrations.CreateModel(
            name='PagoIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio', models.CharField(choices=[('TARJETA', 'TARJETA'), ('QR', 'QR'), ('BILLETERA', 'BILLETERA'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=15)),
                ('pasarela', models.CharField(blank=True, max_length=40, null=True)),
                ('estado', models.CharField(choices=[('CREADO', 'CREADO'), ('EN_PROCESO', 'EN_PROCESO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('EXPIRO', 'EXPIRO')], default='CREADO', max_length=16)),
                ('transaccion_id', models.CharField(blank=True, max_length=120, null=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pago', models.ForeignKey(blank=True, db_column='pago_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.pago')),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, to='propiedades.unidad')),
            ],
            options={
                'db_table': 'pagos_intentos',
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'SOLICITADO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('EJECUTADO', 'EJECUTADO')], default='SOLICITADO', max_length=16)),
                ('pasarela_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pago', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, to='finanzas.pago')),
            ],
            options={
                'db_table': 'reembolsos',
            },
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['unidad', 'periodo'], name='cargos_unidad__b1e07d_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['estado'], name='cargos_estado_8609f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('unidad', 'concepto', 'periodo'), name='uq_cargo'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('condominio', 'numero'), name='uq_documento_numero'),
        ),
    ]
