# Generated by Django 5.2.5 on 2025-09-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condominios',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='propiedades.condominio')),
            ],
            options={
                'db_table': 'unidades',
                'unique_together': {('condominio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='copropietarios', to='propiedades.unidad')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='copropiedades', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'usuarios_unidades',
                'unique_together': {('usuario', 'unidad', 'fecha_inicio')},
            },
        ),
    ]
