# Generated by Django 5.2.5 on 2025-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
        ('seguridad', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='foto_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('INGRESO', 'INGRESO'), ('SALIDA', 'SALIDA'), ('CANCELADA', 'CANCELADA')], default='PENDIENTE', max_length=12),
        ),
        migrations.AlterField(
            model_name='visita',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['unidad', 'estado'], name='visitas_unidad__3d45df_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['visitante'], name='visitas_visitan_9bf361_idx'),
        ),
    ]
