# Generated by Django 5.2.5 on 2025-09-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('propiedades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('requiere_pago', models.BooleanField(default=False)),
                ('costo_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('politica', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, to='propiedades.condominio')),
            ],
            options={
                'db_table': 'areas_comunes',
                'unique_together': {('condominio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('asistentes', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=140, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='reservas.areacomun')),
                ('solicitante', models.ForeignKey(db_column='solicitante_id', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='ReservaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, to='finanzas.pago')),
                ('reserva', models.ForeignKey(db_column='reserva_id', on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
            options={
                'db_table': 'reservas_pagos',
            },
        ),
    ]
