# Generated by Django 5.2.5 on 2025-10-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_add_codigo_tipo_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagointento',
            name='bnb_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagointento',
            name='bnb_qr_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pagointento',
            name='bnb_qr_image_b64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagointento',
            name='bnb_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
