# Generated by Django 5.2.5 on 2025-09-22 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.TextField(unique=True)),
                ('correo', models.TextField(unique=True)),
                ('nombre_completo', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('hash_contrasena', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_login_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
