# Generated by Django 5.2.5 on 2025-09-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('propiedades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaasignacion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tareaasignacion',
            name='tarea',
            field=models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AlterField(
            model_name='tareacomentario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tareacomentario',
            name='tarea',
            field=models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AlterField(
            model_name='tareaevidencia',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tareaevidencia',
            name='tarea',
            field=models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ASIGNADA', 'ASIGNADA'), ('EN_CURSO', 'EN_CURSO'), ('RESUELTA', 'RESUELTA'), ('CERRADA', 'CERRADA'), ('PAUSADA', 'PAUSADA')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'BAJA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')], max_length=8),
        ),
        migrations.AddIndex(
            model_name='tareamantenimiento',
            index=models.Index(fields=['estado', 'prioridad'], name='tareas_mant_estado_2cac52_idx'),
        ),
    ]
