# Generated by Django 5.2.5 on 2025-09-28 20:51

import django.db.models.deletion
import django.utils.timezone
import myapp.comunicacion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('prioridad', models.CharField(choices=[('INFO', 'Informativo'), ('ALERTA', 'Alerta'), ('URGENTE', 'Urgente')], default='INFO', max_length=10)),
                ('alcance', models.CharField(choices=[('TODOS', 'Todos'), ('CONDOMINIO', 'Condominio'), ('UNIDAD', 'Unidad')], default='TODOS', max_length=12)),
                ('condominio_id', models.IntegerField(blank=True, null=True)),
                ('unidad_id', models.IntegerField(blank=True, null=True)),
                ('vence_at', models.DateTimeField(blank=True, null=True)),
                ('publicado_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_activo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publicado_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=myapp.comunicacion.models.aviso_upload_to)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('subido_at', models.DateTimeField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='comunicacion.aviso')),
            ],
        ),
        migrations.CreateModel(
            name='LecturaAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_at', models.DateTimeField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='comunicacion.aviso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'aviso'], name='comunicacio_usuario_7e72d3_idx')],
                'unique_together': {('aviso', 'usuario')},
            },
        ),
    ]
