# Generated by Django 5.2.5 on 2025-09-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('especie', models.CharField(max_length=30)),
                ('raza', models.CharField(blank=True, max_length=40, null=True)),
                ('tamano', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('esterilizada', models.BooleanField(default=False)),
                ('peligrosa', models.BooleanField(default=False)),
                ('autorizada', models.BooleanField(default=True)),
                ('estado', models.CharField(default='ACTIVA', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, db_column='responsable_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarios')),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, to='propiedades.unidad')),
            ],
            options={
                'db_table': 'mascotas',
                'unique_together': {('unidad', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TITULAR', 'TITULAR'), ('INQUILINO', 'INQUILINO'), ('FAMILIAR', 'FAMILIAR')], max_length=15)),
                ('estado', models.CharField(default='ACTIVO', max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, to='propiedades.unidad')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'residencias',
                'unique_together': {('usuario', 'unidad', 'fecha_ingreso')},
            },
        ),
    ]
