# Generated by Django 5.2.5 on 2025-09-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(default='MEDIA', max_length=8)),
                ('estado', models.CharField(default='PENDIENTE', max_length=15)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, to='propiedades.condominio')),
                ('creada_por', models.ForeignKey(db_column='creada_por', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuarios')),
                ('unidad', models.ForeignKey(blank=True, db_column='unidad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedades.unidad')),
            ],
            options={
                'db_table': 'tareas_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TareaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('tarea', models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'db_table': 'tareas_evidencias',
            },
        ),
        migrations.CreateModel(
            name='TareaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuarios')),
                ('tarea', models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'db_table': 'tareas_comentarios',
            },
        ),
        migrations.CreateModel(
            name='TareaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_a', models.ForeignKey(db_column='asignado_a', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuarios')),
                ('tarea', models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'db_table': 'tareas_asignaciones',
            },
        ),
    ]
