# Generated by Django 5.2.5 on 2025-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areacomun',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='creado_en',
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CONFIRMADA', 'CONFIRMADA'), ('RECHAZADA', 'RECHAZADA'), ('CANCELADA', 'CANCELADA'), ('USADA', 'USADA'), ('EXPIRADA', 'EXPIRADA')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservapago',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['area', 'inicio', 'fin'], name='reservas_area_id_57f6ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='areacomun',
            constraint=models.UniqueConstraint(fields=('condominio', 'nombre'), name='uq_area_nombre'),
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='creado_en',
        ),
    ]
