# Generated by Django 5.2.5 on 2025-09-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_areacomun_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areacomun',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False, 'ordering': ['-inicio', '-id']},
        ),
        migrations.AlterModelOptions(
            name='reservapago',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
