# Generated by Django 5.2.5 on 2025-09-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('doc_id', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visitantes',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=140, null=True)),
                ('vehiculo_placa', models.CharField(blank=True, max_length=20, null=True)),
                ('ingreso_previsto', models.DateTimeField(blank=True, null=True)),
                ('ingreso_real', models.DateTimeField(blank=True, null=True)),
                ('salida_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(db_column='registrado_por', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuarios')),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, to='propiedades.unidad')),
                ('visitante', models.ForeignKey(db_column='visitante_id', on_delete=django.db.models.deletion.CASCADE, to='seguridad.visitante')),
            ],
            options={
                'db_table': 'visitas',
            },
        ),
    ]
